# call tool gives useful error

    Code
      call_tool("foo", c(1, 2, 3))
    Output
      [1] "Error calling tool: second argument must be a list"

